# Generated by Django 3.0.7 on 2020-07-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200709_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Degree',
            field=models.CharField(choices=[('Student', 'Student'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctor', 'Doctor')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Qualifications',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
