# Generated by Django 3.0.7 on 2021-08-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20200705_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.TextField(choices=[('FullTime', 'FullTime'), ('PartTime', 'PartTime')], max_length=15),
        ),
    ]
