# Generated by Django 3.0.7 on 2021-08-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20210830_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FullTime', 'FullTime'), ('PartTime', 'PartTime')], max_length=15),
        ),
    ]
