# Generated by Django 3.0.7 on 2021-08-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20210830_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
